/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    'notFound': RouteRecordInfo<'notFound', '/:pathMatch(.*)', Record<never, never>, Record<never, never>>,
    'error': RouteRecordInfo<'error', '/error/:code(\d+)', Record<never, never>, Record<never, never>>,
    'info_': RouteRecordInfo<'info_', '/info', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'system_': RouteRecordInfo<'system_', '/system', Record<never, never>, Record<never, never>>,
    'system_dicts': RouteRecordInfo<'system_dicts', '/system/dicts', Record<never, never>, Record<never, never>>,
    'system_roles': RouteRecordInfo<'system_roles', '/system/roles', Record<never, never>, Record<never, never>>,
    'system_users': RouteRecordInfo<'system_users', '/system/users', Record<never, never>, Record<never, never>>,
    'user_': RouteRecordInfo<'user_', '/user', Record<never, never>, Record<never, never>>,
  }
}
